// Code generated by protoc-gen-go. DO NOT EDIT.
// source: onekreq.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Onekreq struct {
	Id                   uint64   `protobuf:"varint,17,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Onekreq) Reset()         { *m = Onekreq{} }
func (m *Onekreq) String() string { return proto.CompactTextString(m) }
func (*Onekreq) ProtoMessage()    {}
func (*Onekreq) Descriptor() ([]byte, []int) {
	return fileDescriptor_onekreq_9dc40a326caa75fe, []int{0}
}
func (m *Onekreq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Onekreq.Unmarshal(m, b)
}
func (m *Onekreq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Onekreq.Marshal(b, m, deterministic)
}
func (dst *Onekreq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Onekreq.Merge(dst, src)
}
func (m *Onekreq) XXX_Size() int {
	return xxx_messageInfo_Onekreq.Size(m)
}
func (m *Onekreq) XXX_DiscardUnknown() {
	xxx_messageInfo_Onekreq.DiscardUnknown(m)
}

var xxx_messageInfo_Onekreq proto.InternalMessageInfo

func (m *Onekreq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Onekreq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Onekreq)(nil), "main.onekreq")
}

func init() { proto.RegisterFile("onekreq.proto", fileDescriptor_onekreq_9dc40a326caa75fe) }

var fileDescriptor_onekreq_9dc40a326caa75fe = []byte{
	// 89 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0xcf, 0x4b, 0xcd,
	0x2e, 0x4a, 0x2d, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53,
	0xd2, 0xe5, 0x62, 0x87, 0x0a, 0x0b, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x08, 0x2a, 0x30, 0x6a,
	0xb0, 0x04, 0x31, 0x65, 0xa6, 0x08, 0x09, 0x71, 0xb1, 0xa4, 0x24, 0x96, 0x24, 0x4a, 0x30, 0x29,
	0x30, 0x6a, 0xf0, 0x04, 0x81, 0xd9, 0x49, 0x6c, 0x60, 0xbd, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xe2, 0x6f, 0xf0, 0x61, 0x4c, 0x00, 0x00, 0x00,
}
